drop table stax_code_onderdeel cascade constraints;
drop table stax_code_soortobject cascade constraints;
drop table stax_controle_objecten cascade constraints;
drop table stax_eigenaar_gebruiker cascade constraints;
drop table stax_extra_adres cascade constraints;
drop table stax_identif_marktinfo cascade constraints;
drop table stax_kadaster_identif cascade constraints;
drop table stax_kadaster_object cascade constraints;
drop table stax_marktinfo cascade constraints;
drop table stax_marktinfo_kadaster cascade constraints;
drop table stax_marktinfo_woz cascade constraints;
drop table stax_onderbouw_onderd cascade constraints;
drop table stax_onderbouwing cascade constraints;
drop table stax_sluimer_woz cascade constraints;
drop table stax_status_beschikking cascade constraints;
drop table stax_subject_30 cascade constraints;
drop table stax_subject_31 cascade constraints;
drop table stax_tussentijd_taxatie cascade constraints;
drop table stax_voorloop cascade constraints;
drop table stax_wozobject cascade constraints;

drop sequence stax_code_onderdeel_id_seq;
drop sequence stax_code_soortobject_id_seq;
drop sequence stax_controle_objecten_id_seq;
drop sequence stax_eigenaar_gebruiker_id_seq;
drop sequence stax_extra_adres_id_seq;
drop sequence stax_identif_marktinfo_id_seq;
drop sequence stax_kadaster_identif_id_seq;
drop sequence stax_kadaster_object_id_seq;
drop sequence stax_marktinfo_id_seq;
drop sequence stax_marktinfo_kadaster_id_seq;
drop sequence stax_marktinfo_woz_id_seq;
drop sequence stax_onderbouw_onderd_id_seq;
drop sequence stax_onderbouwing_id_seq;
drop sequence stax_sluimer_woz_id_seq;
drop sequence stax_status_beschikking_id_seq;
drop sequence stax_subject_30_id_seq;
drop sequence stax_subject_31_id_seq;
drop sequence stax_tussentijd_taxatie_id_seq;
drop sequence stax_voorloop_id_seq;
drop sequence stax_wozobject_id_seq;
